apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2026-02OTUS/mikesmr-admin_repo.git   # <-- HTTPS
    targetRevision: kubernetes-gitops
    path: .github/kubernetes-networks
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    syncOptions:
      - CreateNamespace=true