apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-metrics-deployment
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-metrics
  template:
    metadata:
      labels:
        app: nginx-metrics
    spec:
      containers:
      - name: nginx
        image: custom-nginx-metrics:latest
        imagePullPolicy: Never  # Важно: использовать локальный образ, не пытаться его скачать
        ports:
        - containerPort: 80