# nginx.conf
server {
    listen       80;
    server_name  localhost;

    # Основной эндпоинт для метрик
    location = /metrics {
        stub_status;
        # Опционально: разрешить доступ только с определенных IP
        # allow 127.0.0.1;
        # deny all;
    }

    # Опционально: стандартная страница-заглушка для проверки работы
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}   