server {
    listen       80;
    server_name  localhost;

    # --- Эндпоинт для Prometheus Exporter ---
    location = /stub_status {
        stub_status on;
        access_log off;
        # Ограничиваем доступ только к exporter'у, который будет в том же поде
        allow 127.0.0.1;
        deny all;
    }

    # --- Эндпоинт, который вы создали ранее для прямого доступа ---
    location = /metrics {
        stub_status;
    }

    # Остальная ваша конфигурация...
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}