apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics-service
  namespace: homework
spec:
  selector:
    app: nginx-metrics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Для доступа извне Minikube