apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-test-nginx
spec:
  containers:
    - name: app
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "$(date) - Writing to S3" >> /data/test-file.txt;
            sleep 30;
          done
      volumeMounts:
        - mountPath: /data
          name: webroot
  volumes:
    - name: webroot
      persistentVolumeClaim:
        claimName: csi-s3-pvc
        readOnly: false