apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
stringData:
  accessKeyID: <access_key_ID>
  secretAccessKey: <secret_key>
  endpoint: https://storage.yandexcloud.net